"""empty message

Revision ID: 0ef2e1ad3826
Revises: e2f35d585552
Create Date: 2023-02-24 22:42:37.602615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef2e1ad3826'
down_revision = 'e2f35d585552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historia', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historia', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
