"""empty message

Revision ID: 983a7572c19f
Revises: 
Create Date: 2023-03-01 04:27:03.281454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983a7572c19f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('lastname', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('historia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('telef', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=100), nullable=True),
    sa.Column('paisRes', sa.String(length=15), nullable=True),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.Column('alt', sa.String(length=4), nullable=True),
    sa.Column('cirugiasAnt', sa.String(length=200), nullable=True),
    sa.Column('especif', sa.String(length=200), nullable=True),
    sa.Column('alergias', sa.String(length=200), nullable=True),
    sa.Column('especify', sa.String(length=200), nullable=True),
    sa.Column('obs', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id_passport', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('confirmation_number', sa.Integer(), nullable=False),
    sa.Column('transaction_person', sa.String(length=20), nullable=False),
    sa.Column('image_of_payment', sa.String(length=200), nullable=False),
    sa.Column('image_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirmation_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago')
    op.drop_table('historia')
    op.drop_table('user')
    # ### end Alembic commands ###
